### ISSUE TITLE
doesn't work with conda 4.3

### ISSUE THREAD

**Issue by lexual** [SciTools/conda-gitenv#30]
```
$ conda gitenv resolve .
Traceback (most recent call last):
  File "/home/ahider/miniconda3/bin/conda-gitenv", line 11, in <module>
    load_entry_point('conda-gitenv==0.2.2', 'console_scripts', 'conda-gitenv')()
  File "/home/ahider/miniconda3/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/home/ahider/miniconda3/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/home/ahider/miniconda3/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2258, in load
  File "/home/ahider/miniconda3/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/home/ahider/miniconda3/lib/python2.7/site-packages/conda_gitenv/cli.py", line 6, in <module>
    import conda_gitenv.resolve as resolve
  File "/home/ahider/miniconda3/lib/python2.7/site-packages/conda_gitenv/resolve.py", line 22, in <module>
    import conda_build_all.version_matrix
  File "/home/ahider/miniconda3/lib/python2.7/site-packages/conda_build_all/version_matrix.py", line 19, in <module>
    for attr in ['Unsatisfiable', 'NoPackagesFound'])
  File "/home/ahider/miniconda3/lib/python2.7/site-packages/conda_build_all/version_matrix.py", line 19, in <genexpr>
    for attr in ['Unsatisfiable', 'NoPackagesFound'])
AttributeError: 'module' object has no attribute 'NoPackagesFound'
```

reverting back to conda 4.2 fixes this.

**Comment by lexual** [comment]
hmm, actually a conda_build_all bug I think.

```
$ python -c 'import conda_build_all.version_matrix'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ahider/miniconda3/lib/python2.7/site-packages/conda_build_all/version_matrix.py", line 19, in <module>
    for attr in ['Unsatisfiable', 'NoPackagesFound'])
  File "/home/ahider/miniconda3/lib/python2.7/site-packages/conda_build_all/version_matrix.py", line 19, in <genexpr>
    for attr in ['Unsatisfiable', 'NoPackagesFound'])
AttributeError: 'module' object has no attribute 'NoPackagesFound'
```
